# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties (check https://fabricmc.net/develop)
minecraft_version=26.2
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=0.1.0
maven_group=com.fruitfly
archives_base_name=fruitfly-connectome

# Dependencies
fabric_version=0.161.0+26.2
